WIP API provides functionality for user to have different roles
CraftAcademy/news_in_progress_api pull request #10
Opened 2021-10-20 07:12 UTC by Fraseer

2021-10-20 08:06 UTC, tochman commented on spec/factories/user.rb
> +end
```ruby
FactoryBot.define do
  factory :user do
    email { 'example@email.com' }
    password { '1234' }
    factory :editor do
       role { :editor }
     end
    factory :journalist do
       role { :journalist }
     end
  end
end
```

2021-10-23 06:40 UTC, maxarvid commented on spec/models/user_spec.rb
> +      let(:user_2) { create(:journalist) }
It might be superfluous to have `user_2` for this particular test. We are not testing that an article can have many authors, but rather that the `subject`, in this case a journalist can be called with `.articles`

2021-10-23 06:44 UTC, maxarvid commented on spec/policies/article_policies_spec.rb
> +    describe 'the user editor and not an author' do
Missing an `is` in this sentence

2021-10-23 06:45 UTC, maxarvid commented on spec/policies/article_policies_spec.rb
> +    describe 'the user editor and an author' do
same as above

2021-10-23 06:48 UTC, maxarvid commented on spec/requests/api/create_article_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
I don't think these lines are necessary , they repeat line 3 and 5

2021-10-23 06:49 UTC, maxarvid commented on spec/requests/api/create_article_spec.rb
> +  let(:user_2) { create(:user) }
Looks to me as though `user_2` does not come into play below

2021-10-23 06:52 UTC, maxarvid commented on spec/user_roles/users_create_articles_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
This could lead to some false positives. Let's create a user so we can specify what credentials we are creating here

2021-10-23 06:53 UTC, maxarvid commented on spec/user_roles/users_show_article_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
Same as in the other users spec file. This could lead to false positives

2021-10-23 06:56 UTC, maxarvid requested changes
Left a couple of things, mostly in the specs that I think need to be addressed.

2021-10-23 10:07 UTC, Fraseer commented on spec/models/user_spec.rb
> +      let(:user_2) { create(:journalist) }
Good point, probably want to test for multiple articles here instead

2021-10-23 10:11 UTC, Fraseer commented on spec/requests/api/create_article_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
Removed

2021-10-23 10:11 UTC, Fraseer commented on spec/requests/api/create_article_spec.rb
> +  let(:user_2) { create(:user) }
It does not

2021-10-23 10:15 UTC, Fraseer commented on spec/user_roles/users_create_articles_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
So my thinking here was we create users within each of the describe blocks, each with different roles, and then have the same device auth credentials for each of them. This way every user is authorised in the device sense, and then its the role authorisations we are testing further on

2021-10-23 10:16 UTC, Fraseer commented on spec/user_roles/users_create_articles_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
Im 99% sure it works as described

2021-10-23 10:16 UTC, Fraseer commented on spec/user_roles/users_show_article_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
see above

2021-10-23 10:20 UTC, Fraseer commented on spec/user_roles/users_create_articles_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
Yeah so if you change the name of say the editor to something other than user, it then lacks the ability to make changes as it does not have the device auth credentials. Meaning that as each time we create a user in the describe blocks, called user, we are using the credentials created up the top

2021-10-23 10:27 UTC, maxarvid commented on spec/user_roles/users_create_articles_spec.rb
> +  let(:credentials) { user.create_new_auth_token }
If it works it works. In my mind the credentials pointed to a particular user in the `users` table. But if it's smart enough to check the roles independently then we are of course good.

2021-10-23 10:29 UTC, maxarvid approved these changes
LGTM

2021-10-24 08:11 UTC, lukeperrin10 approved these changes
Looks good. Just fix those for matters, couple of spaces added here and there which just makes for extra reading. Even an extra file in one example. 2 make sure you do some manual testing as well.spin up the rails server and point your client side to the local host. Do it for every feature. So there is no panic when a bug creeps in to production.

2021-10-24 08:11 UTC, lukeperrin10 commented on spec/models/article_spec.rb
> +    it { is_expected.to have_db_column :published }
Thought the formatter issues were fixed?

2021-10-24 08:12 UTC, merged