API allows for article published status
CraftAcademy/news_in_progress_api pull request #9
Opened 2021-10-18 10:36 UTC by dorianbuck

PT: https://www.pivotaltracker.com/story/show/179892938

## User Story
```
As a news API
In order to move articles through editorial pipeline
I would like to include a published category
```

## Tasks
- Create `published` column in `articles` table- Create user model
- Make `published` column contain boolean values, set default to false
- Modify `index` action in `articles_controller.rb` to only return published articles

## Screenshot

![Skärmavbild 2021-10-18 kl  12 32 57](https://user-images.githubusercontent.com/29585462/137715298-8a079025-246d-482d-8112-b77f3f574811.png)
![Skärmavbild 2021-10-18 kl  12 33 37](https://user-images.githubusercontent.com/29585462/137715303-21dbd3c7-0bcc-4bcb-bf20-7a18d4f53b0a.png)

2021-10-18 10:44 UTC, maxarvid commented on spec/models/article_spec.rb
> +    # it { is_expected.to validate_presence_of :published }
Should this comment be here?

2021-10-18 10:49 UTC, dorianbuck commented on spec/models/article_spec.rb
> +    # it { is_expected.to validate_presence_of :published }
This has been removed

2021-10-18 17:04 UTC, offcast-dev reviewed
Refactor new specs to existing files. Add functionality so Article index action do not return articles that are not published

2021-10-18 17:04 UTC, SevaDer14 commented on spec/requests/api/article_published_status_spec.rb
> +end
I don't see why you need separate test file for this. I think you can include asserting published status in already existing index or show spec

2021-10-18 17:04 UTC, SevaDer14 commented on spec/requests/api/article_published_status_spec.rb
> +end
Also I think if article is not published you probably don't want to see it returned by index action? I don't see not test nor functionality for that. If you planned that as separate feature I say you should include it here as just having published status is not a feature in of itself.

2021-10-18 18:10 UTC, dorianbuck commented on spec/requests/api/article_published_status_spec.rb
> +end
This has been adjusted. Thank you for your valuable input!
![Skärmavbild 2021-10-18 kl  20 06 32](https://user-images.githubusercontent.com/29585462/137784704-95934e2e-b011-47f9-a865-37e10907b7cc.png)

2021-10-19 05:34 UTC, tochman requested changes
The changes proposed are not connected to the title and user story. Please read the story carefully and consider what it is you are implementing. This is just an observation on my part. 

Besides that, please do not forget about thin controllers and fat models. Consider extracting the filtering of published articles to the model.

2021-10-19 05:34 UTC, tochman commented on db/migrate/20211018095905_add_published_status_to_articles.rb
> +    add_column :articles, :published, :boolean
What is the default state of this attribute?

2021-10-19 05:36 UTC, tochman approved these changes

2021-10-19 06:13 UTC, offcast-dev reviewed
.all may be redundant

2021-10-19 06:13 UTC, SevaDer14 commented on app/controllers/api/articles_controller.rb
> +      articles_published.all
Are you sure you need .all here?

2021-10-19 06:13 UTC, SevaDer14 commented on app/controllers/api/articles_controller.rb
> +      articles_published.all
I think it will work without it

2021-10-19 06:31 UTC, dorianbuck commented on app/controllers/api/articles_controller.rb
> +      articles_published.all
It works without

2021-10-19 11:46 UTC, lukeperrin10 commented on .ruby-version
> +ruby-2.5.1
why the change?

2021-10-19 12:00 UTC, lukeperrin10 commented on spec/requests/api/articles_index_spec.rb
> +      expect(response_json['message']).to eq "There are no articles in the database"
This one doesn't make sense to me really. The assertion is that it is not expected to return an unpublished article. But the response message is "There are no articles in the database". My point is here you test for an article that has a status that is published: false. I would prefer to see a test where there are multiple articles with different published values that actually show it is only returning the published articles. This is only testing if the articles DB is empty.

2021-10-19 12:00 UTC, lukeperrin10 requested changes
Need to look at your tests. See comment

2021-10-19 12:02 UTC, Fraseer commented on .ruby-version
> +ruby-2.5.1
Because Johnny cannot install 3.0.2 so we all revert so he could code along

2021-10-19 12:04 UTC, lukeperrin10 commented on .ruby-version
> +ruby-2.5.1
ok, my suggestion would be that this is set from the start of any project dependent on everyone's setup. Something to think about in future. Versions and dependencies changing in the middle of a project should be done cautiously.

2021-10-19 12:10 UTC, lukeperrin10 approved these changes
Ok, looks good now, just think about what you're testing.

2021-10-19 12:13 UTC, merged